security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        main:
            pattern: ^/
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login
            entry_point: form_login

    access_control:
    - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
    - { path: ^/login,           roles: PUBLIC_ACCESS }
    - { path: ^/logout,          roles: PUBLIC_ACCESS }
    - { path: ^/register,        roles: PUBLIC_ACCESS }
    - { path: ^/,                roles: PUBLIC_ACCESS }



# konfiguracja do testów...
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

