controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
api_login_check:
    path: /api/login_check

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_home:
    path: /
    controller: App\Controller\HomeController::index

