parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\PostVoter:
        tags:
            - { name: security.voter }

    App\EventListener\ExceptionListener:    
        arguments:
            $logger: '@logger'
            $params: '@parameter_bag'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
